/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void rollTest() {

        assertEquals("The method 'rolls' should return an array of integers with a length of 4 index positions",
                4,
                Library.roll(4).length);


    }
    @Test public void TestcontainsDuplicates() {
        int[] inputArray = {1,1,2};
        boolean actual = Library.containsDuplicates(inputArray);
        assertTrue("the method returns a boolean value of either true or false",
                actual);
    }
    @Test public void TestCalculatingAverages() {
    int[] testArray = {1,2,4};
    int average = 2;
    assertEquals("The method should return the average of the numbers in the array",
            average,
            Library.calculatingAverages(testArray)

    );

    }
}