/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static int[] roll(int n) {
        int[] rollResults = new int[n];
        Random random = new Random();
        int rand = 0;
        while (true) {
            rand = random.nextInt(6);
            if (rand != 0) break;
        }
        return rollResults;
    }
    public static boolean containsDuplicates(int[]){

    }
}
//got some help from GeeksForGeeks on using nextINT and break

